# Generated by Django 5.1 on 2024-09-03 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_voicerecording_cloned'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicerecording',
            name='text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
