# Generated by Django 5.1 on 2024-09-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_voicerecording_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicerecording',
            name='text_language',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
